version: 2.1
executors:
  node-executor: #Defines the executor docker image here
    docker:
      - image: cimg/node:16.15

jobs:
  build:
    executor: node-executor #use custom executor defines above
    steps:
      - checkout
      - run:
          name: 'Run Semantic release to build and generate .version file'
          command: |
            npm install
            npx lerna init
workflows:
  build-test:
    jobs:
      - build
